### ISSUE TITLE
TypeError: can only concatenate list (not "dict_keys") to list using ATACPrimerTool on my own data

### ISSUE THREAD

**Issue by El-Castor** [ChangLab/ATACPrimerTool#7]
Hi, 

Thanks for your useful tool, I want to design primer to validate a differential ACRs underlight. 

But When I launch the command I have this error :

```bash
python3 $ATACPrimerTool_DIR/pipelines/ATACPrimerTool.py -I $BAM_DIR -B $bedFileRegionToDesign_PATH -O $output_DIR -S $sampleName -G "CMiso" -fasta $genome_PATH -C $genome_PATH
Traceback (most recent call last):
  File "/opt/share/OTHER_Software/VIRTUALENV/ATACPrimerTool/ATACPrimerTool/pipelines/ATACPrimerTool.py", line 20, in <module>
    parser = pypiper.add_pypiper_args(parser, groups=["config"], args=["sample-name", "recover", "dirty", "new-start", "output-parent", "genome"])
  File "/opt/share/OTHER_Software/VIRTUALENV/ATACPrimerTool/lib/python3.7/site-packages/pypiper/utils.py", line 60, in add_pypiper_args
    argument_groups=groups, arguments=args, use_all_args=all_args)
  File "/opt/share/OTHER_Software/VIRTUALENV/ATACPrimerTool/lib/python3.7/site-packages/pypiper/utils.py", line 812, in _determine_args
    LOGGING_CLI_OPTDATA.keys(),
TypeError: can only concatenate list (not "dict_keys") to list
```

with these argument : 

```bash
# TOOL set up
ATACPrimerTool_DIR="/opt/share/OTHER_Software/VIRTUALENV/ATACPrimerTool/ATACPrimerTool"

configFile_PATH="/NetScratch/cpichot/ATACseq_analysis/ATACseq_cytometrie_dec2019_flowers_FMH_rep4_100K/build-Primer-ATACqPCR/config/ATACPrimerTool_config.yaml"

# INPUT

BAM_DIR="/NetScratch/cpichot/ATACseq_analysis/ATACseq_cytometrie_dec2019_flowers_FMH_rep4_100K/genrich_analysis_fullData/sorted_bam_files/male"

bedFileRegionToDesign_PATH="/NetScratch/cpichot/ATACseq_analysis/ATACseq_cytometrie_dec2019_flowers_FMH_rep4_100K/build-Primer-ATACqPCR/regionTodesign.bed"

sampleName="peaksMale-WIP1-down3UTR"

genome_PATH="/K/FLOCAD/Bioinfo/Workspace/ClementP/DavidL/Genome/CMiso11/CMiso1.1_genome.fa"
```

Do you know how I can fix this error please ?

Thanks in advance

**Comment by El-Castor** [comment]
Hi, 

We found out where the error came from. This is a version issue of the pypiper package. This has been updated since the development of the tool. To solve the problem it is necessary to install the version release v 0.10.0 of pypiper using pip. Now everything is working fine.

thanks.

**Comment by katieyost** [comment]
Thanks for letting me know! I'll add this to the README and close the issue.
