### ISSUE TITLE
Python error "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by samfux84** [ChangLab/ATACPrimerTool#9]
Hi,

I am trying to install ATACPrimerTool on our HPC cluster. I followed the installation instructions and I have all required dependencies available, but still I am getting a Python error when running cmd.sh:

```
[sfux@eu-login-28 ~]$ module load atacprimertool/1.0
[sfux@eu-login-28 ~]$ module lsit

Currently Loaded Modules:
  1) StdEnv   2) gcc/4.8.5   3) python/2.7.14   4) bedtools2/2.26.0   5) samtools/1.6   6) r/3.5.1   7) atacprimertool/1.0



[sfux@eu-login-28 ~]$ cmd.sh
Traceback (most recent call last):
  File "/cluster/apps/nss/atacprimertool/1.0/x86_64/pipelines/ATACPrimerTool.py", line 13, in <module>
    import pypiper
  File "/cluster/apps/gcc-4.8.5/python-2.7.14-uqv45r3i7uhftidsinof7qu3sdcqdcis/lib/python2.7/site-packages/pypiper/__init__.py", line 2, in <module>
    from .manager import *
  File "/cluster/apps/gcc-4.8.5/python-2.7.14-uqv45r3i7uhftidsinof7qu3sdcqdcis/lib/python2.7/site-packages/pypiper/manager.py", line 29, in <module>
    from attmap import AttMapEcho
  File "/cluster/apps/gcc-4.8.5/python-2.7.14-uqv45r3i7uhftidsinof7qu3sdcqdcis/lib/python2.7/site-packages/attmap/__init__.py", line 3, in <module>
    from ._att_map_like import AttMapLike
  File "/cluster/apps/gcc-4.8.5/python-2.7.14-uqv45r3i7uhftidsinof7qu3sdcqdcis/lib/python2.7/site-packages/attmap/_att_map_like.py", line 81
    return f"\n{prefix} - " + f"\n{prefix} - ".join([str(i) for i in obj])
                          ^
SyntaxError: invalid syntax
[sfux@eu-login-28 ~]$
```

Is this a known problem? And how can I resolve this.

Any help is appreciated.

Best regards

Sam

**Comment by samfux84** [comment]
This question is without answer for more than 3 months. Is the software still maintained?

**Comment by katieyost** [comment]
Hi Sam - this looks like it could be an issue loading pypiper. Do you have pypiper v0.10.0 installed?

**Comment by katieyost** [comment]
Hi - this seems to be a conflict with the attmap version. `pip install attmap==0.12.11` should resolve this.

**Comment by samfux84** [comment]
@katieyost Thank you very much for your reply. I downgraded attmap to 0.12.11 and now importing pypiper does not result in an error anymore.

Best regards and thank you again.

Sam
